# Generated by Django 4.0.4 on 2023-08-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='astronomyshow',
            name='show_themes',
            field=models.ManyToManyField(blank=True, to='planetarium.showtheme'),
        ),
    ]
